"use client";

import RaceList from "@/components/race-list";
import { Race } from "@/models/races.model";
import { fetchRaces, saveRace } from "@/services/races.services";
import Form from "next/form";
import { useState, useEffect } from "react";

export default function RaceClient({
  prefetchedRaces,
}: {
  prefetchedRaces: Race[];
}) {
  const [races, setRaces] = useState<Race[]>(prefetchedRaces || []);

  useEffect(() => {
    async function fetchData() {
      const data = await fetchRaces();
      setRaces(data);
    }

    fetchData();
  }, []);

  async function onSubmit(data: FormData) {
    try {
      const newRace: Race = {
        // id is auto-generated by the database
        id: "",
        name: data.get("name") as string,
      };

      // saving logic delegated to the specific service function
      const result = await saveRace(newRace);
      console.log("New race added:", result);

      // update UI
      setRaces((prevRaces) => [...prevRaces, result]);
    } catch (error) {
      console.error("Error adding race:", error);
    }
  }

  return (
    <div>
      <div className="flex gap-4 items-center flex-col sm:flex-row">
        <Form className="flex gap-4" action={onSubmit}>
          <input
            type="text"
            id="name"
            name="name"
            required
            className="border border-gray-300 rounded px-4 py-2 w-full"
            placeholder="Enter race name"
          />
          <button
            type="submit"
            className="bg-gray-800 text-white px-4 py-2 rounded hover:bg-gray-900 transition-colors duration-200"
          >
            Add
          </button>
        </Form>
      </div>

      <div className="mt-8">
        <h2 className="text-2xl font-bold text-center sm:text-left mb-4">
          Race List :{" "}
        </h2>
        <ul>
          {races.map((race) => (
            <li
              key={race.id}
              className="text-sm/6 text-center sm:text-left font-[family-name:var(--font-geist-mono)] font-semibold mb-2 tracking-[-.01em] underline cursor-pointer"
            >
              {race.name}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
