import { Race } from "@/models/races.model";
import { fetchRaces, saveRace } from "@/services/races.services";
import Form from "next/form";

export default function AddRaceForm() {
  // use Form from next/form to handle form submission
  return (
    <Form className="flex gap-4" action={onSubmit}>
      <input
        type="text"
        id="name"
        name="name"
        required
        className="border border-gray-300 rounded px-4 py-2 w-full"
        placeholder="Enter race name"
      />
      <button
        type="submit"
        className="bg-gray-800 text-white px-4 py-2 rounded hover:bg-gray-900 transition-colors duration-200"
      >
        Add
      </button>
    </Form>
  );
}

async function onSubmit(data: FormData) {
  "use server"; // Ensure this function runs on the server (required by next/form)

  try {
    const newRace: Race = {
      // id is auto-generated by the database
      id: "",
      name: data.get("name") as string,
    };

    // saving logic delegated to the specific service function
    const result = await saveRace(newRace);
    console.log("New race added:", result);

    // update UI

    // This could be done by re-fetching the races
    const updatedRaces = await fetchRaces();
    console.log("Updated races:", updatedRaces);
  } catch (error) {
    console.error("Error adding race:", error);
  }
}
