name: Build and Test

env:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_POCKETBASE_URL: ${{ secrets.NEXT_PUBLIC_POCKETBASE_URL }}
  POCKETBASE_TOKEN: ${{ secrets.POCKETBASE_TOKEN }}

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.01
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
            - args: [--global, gulp, prettier, vitest]
      - name: 'Lint Code'
        run: pnpm lint
      - name: 'Run Tests'
        run: pnpm test
      - name: 'Build Project'
        run: pnpm build
